version: '3.8'

services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    command: web
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ''
      DATABASE_HOST: db
      BUNDLE_PATH: /bundle/vendor
    ports:
      - '3000:3000'
    networks:
      default:
      mentorship:
        aliases:
          - mentorship
    depends_on:
      - db

  sidekiq:
    build:
      context: .
    stdin_open: true
    tty: true
    command: sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ''
      DATABASE_HOST: db
      BUNDLE_PATH: /bundle/vendor

    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle_path:/bundle

  redis:
    hostname: redis
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis

  db:
    hostname: postgres
    image: postgres:13.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "mentorship_development"
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
  redis:
  bundle_path:

networks:
  mentorship:
    external: true
