default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 }).to_i + (ENV.fetch("RAILS_MAX_THREADS") { 5 }).to_i %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: mentorship_development

test:
  <<: *default
  database: mentorship_test

production:
  <<: *default
  database: mentorship_production
